version: "3.9"
services:
  web:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./site.conf:/etc/nginx/conf.d/default.conf
    
    depends_on:
      - php
  
  php:
    container_name: php
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        PHP_VERSION: '8.2.4-fpm-bullseye'
    volumes:
      - ./:/var/www
    ports:
      - 9000:9000
    depends_on:
      - db

  db:
    container_name: mysql
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=my_new_house
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - "./database:/var/lib/mysql"
    ports:
      - 3306:3306