version: "3.9"
services:
  web:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./site.conf:/etc/nginx/conf.d/default.conf
    
    depends_on:
      - php
    networks:
        appNetwork:
          ipv4_address: 172.24.2.3
  
  php:
    container_name: php
    build:
      dockerfile: ./Dockerfile
      args:
        PHP_VERSION: '8.2.4-fpm-bullseye'
    volumes:
      - ./:/var/www
    ports:
      - 9000:9000
    links:
       - db:db
    networks:
        appNetwork:
          ipv4_address: 172.24.2.1

  db:
    container_name: mysql
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=my_new_house
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - "./database:/var/lib/mysql"
      - ./dump:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    networks:
      appNetwork:
        ipv4_address: 172.24.2.2
    
    

networks:
    appNetwork:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: "172.24.2.0/16"